### PR TITLE
test flow was added to actions

### PR DESCRIPTION
**Pull request by kochurovro**
Hi guys

I added a test flow to Github Actions
If you're interested, I can work on cover bage after the merge

Thank you

### CODE REVIEW

**Comment by chebyrash** [comment]
Thank you for your work Roman
I think we're already using travis for tests, is there a reason we should switch to GitHub Actions?

**Comment by chebyrash** [comment]
@kochurovro Go 1.14 came out, you might want to bump the version

**Comment by chebyrash** [comment]
Let's give this a try

**Comment by kochurovro** [comment]
> is there a reason we should add GitHub Actions?
About it, I don't want to compare TravisCI and Actions. I think usage the eternal toll is better in this case.

**Comment by chebyrash** [comment]
@kochurovro do you want to add an actions badge to the readme (next to the travis one please)?

**Pull request merged**
